
// Lista de profissões mais comuns para autocomplete
export const professions = [
  // Tecnologia da Informação
  "Desenvolvedor de Software",
  "Engenheiro de Software",
  "Analista de Sistemas",
  "Cientista de Dados",
  "Analista de Dados",
  "Engenheiro de Dados",
  "Desenvolvedor Front-end",
  "Desenvolvedor Back-end",
  "Desenvolvedor Full Stack",
  "DevOps",
  "Arquiteto de Soluções",
  "Product Manager",
  "Product Owner",
  "Scrum Master",
  "Analista de Segurança da Informação",
  "Administrador de Redes",
  "Suporte Técnico",
  "DBA (Administrador de Banco de Dados)",
  "Designer de UX/UI",
  "QA / Testador de Software",
  
  // Administração e Gestão
  "Administrador",
  "Gerente de Projetos",
  "Analista Administrativo",
  "Assistente Administrativo",
  "Auxiliar Administrativo",
  "Gerente Comercial",
  "Gerente Financeiro",
  "Gerente de RH",
  "Gerente de Operações",
  "Coordenador Administrativo",
  "Controller",
  "Business Partner",
  
  // Vendas e Marketing
  "Vendedor",
  "Representante Comercial",
  "Consultor de Vendas",
  "Gerente de Vendas",
  "Analista de Marketing",
  "Especialista em Marketing Digital",
  "Social Media",
  "Designer Gráfico",
  "Redator",
  "Publicitário",
  "Analista de E-commerce",
  "Gerente de E-commerce",
  "Trade Marketing",
  "Key Account Manager",
  
  // Recursos Humanos
  "Analista de RH",
  "Analista de Recrutamento e Seleção",
  "Business Partner de RH",
  "Analista de Desenvolvimento Humano",
  "Analista de Folha de Pagamento",
  "Assistente de RH",
  "Coordenador de RH",
  "Gerente de RH",
  
  // Finanças e Contabilidade
  "Contador",
  "Analista Contábil",
  "Assistente Contábil",
  "Auxiliar Contábil",
  "Analista Financeiro",
  "Assistente Financeiro",
  "Tesoureiro",
  "Auditor",
  "Consultor Financeiro",
  
  // Engenharia
  "Engenheiro Civil",
  "Engenheiro Mecânico",
  "Engenheiro Elétrico",
  "Engenheiro de Produção",
  "Engenheiro Químico",
  "Engenheiro Ambiental",
  "Engenheiro de Segurança do Trabalho",
  "Engenheiro de Qualidade",
  "Técnico em Engenharia",
  
  // Saúde
  "Médico",
  "Enfermeiro",
  "Técnico de Enfermagem",
  "Auxiliar de Enfermagem",
  "Fisioterapeuta",
  "Nutricionista",
  "Farmacêutico",
  "Psicólogo",
  "Dentista",
  "Biomédico",
  "Veterinário",
  "Radiologista",
  
  // Educação
  "Professor",
  "Coordenador Pedagógico",
  "Pedagogo",
  "Psicopedagogo",
  "Diretor Escolar",
  "Orientador Educacional",
  
  // Direito e Jurídico
  "Advogado",
  "Assistente Jurídico",
  "Analista Jurídico",
  "Paralegal",
  
  // Logística e Operações
  "Analista de Logística",
  "Coordenador de Logística",
  "Assistente de Logística",
  "Operador de Logística",
  "Motorista",
  "Auxiliar de Estoque",
  "Assistente de Compras",
  "Analista de Compras",
  "Comprador",
  "Almoxarife",
  
  // Atendimento ao Cliente
  "Atendente",
  "Recepcionista",
  "Telefonista",
  "Operador de Telemarketing",
  "Analista de Atendimento",
  "Supervisor de Atendimento",
  "Customer Success",
  "Suporte ao Cliente",
  
  // Outros
  "Arquiteto",
  "Designer de Interiores",
  "Jornalista",
  "Fotógrafo",
  "Chef de Cozinha",
  "Cozinheiro",
  "Garçom",
  "Segurança",
  "Eletricista",
  "Encanador",
  "Mecânico",
  "Técnico de Manutenção",
  "Zelador",
  "Auxiliar de Limpeza",
  "Porteiro",
].sort();

// Tipos de cargo (senioridades)
export const jobTypes = [
  "Menor Aprendiz",
  "Estagiário",
  "Auxiliar",
  "Assistente",
  "Técnico",
  "Analista Jr",
  "Analista Pl",
  "Analista Sr",
  "Supervisor",
  "Coordenador",
  "Gerente",
  "Diretor",
];
